Create `mypy CI` & `Fix mypy typing` errors & add `@beartype` (#151)
* fixed typings for collection

passing mypy

* fixed computation.py typings with mypy

* ignoring list copy typing error
    * in case the list is None the SDk would give an attribute error and it would be no fault of the user

* fixed computation_process.py typings with mypy

* fixed data.py typings with mypy

* fixed experiment.py typings with mypy

* fixed experiment.py typings with mypy

ignored `identifiers: List[dict[str, str]]` typing
getting an error of:
```
error: Argument "default_factory" to "field" has incompatible type "Type[Dict[Any, Any]]"; expected "Callable[[], List[Dict[str, str]]]"  [arg-type]
```

* fixed process.py typings with mypy

* fixed project.py typings with mypy

* fixed reference.py typings with mypy

* fixed algorithm.py typings with mypy

* fixed citation.py typings with mypy

* fixed computational_forcefield.py typings with mypy

* fixed ingredient.py typings with mypy

* fixed parameter.py typings with mypy

* not sure how to fix quantity.py typings

* updated paginator.py typings

* updated api.py typings

* formatting with trunk

* adding `@beartype` to api.py

* adding `@beartype` to paginator.py

* adding `@beartype` to collection.py

* adding `@beartype` to reference.py.py

* adding `@beartype` to project.py.py

* adding `@beartype` to process.py

* adding `@beartype` to primary_base_node.py

* adding `@beartype` to material.py

* adding `@beartype` to inventory.py

* adding `@beartype` to experiment.py

* adding `@beartype` to data.py

* adding `@beartype` to computation_process.py

* adding `@beartype` to software_configuration.py

* adding `@beartype` to software.py

* adding `@beartype` to quantity.py

* adding `@beartype` to property.py

* adding `@beartype` to parameter.py

* adding `@beartype` to ingredient.py

* adding `@beartype` to equipment.py

* adding `@beartype` to condition.py

* adding `@beartype` to computational_forcefield.py

* adding `@beartype` to citation.py

* adding `@beartype` to user.py

* adding `@beartype` to file.py

* Add beartype check (#155)

* adding `@beartype` to api.py

* adding `@beartype` to paginator.py

* adding `@beartype` to collection.py

* adding `@beartype` to reference.py.py

* adding `@beartype` to project.py.py

* adding `@beartype` to process.py

* adding `@beartype` to primary_base_node.py

* adding `@beartype` to material.py

* adding `@beartype` to inventory.py

* adding `@beartype` to experiment.py

* adding `@beartype` to data.py

* adding `@beartype` to computation_process.py

* adding `@beartype` to software_configuration.py

* adding `@beartype` to software.py

* adding `@beartype` to quantity.py

* adding `@beartype` to property.py

* adding `@beartype` to parameter.py

* adding `@beartype` to ingredient.py

* adding `@beartype` to equipment.py

* adding `@beartype` to condition.py

* adding `@beartype` to computational_forcefield.py

* adding `@beartype` to citation.py

* adding `@beartype` to user.py

* adding `@beartype` to file.py

* added "beartype" to `.cspell.json`

* added beartype to requirements_dev.txt

* trunk format

* add beartype requirement

---------

Co-authored-by: Ludwig Schneider <ludwigschneider@uchicago.edu>

* remove unneeded file

* several small mypy issues

* Create mypy_check.yaml

* 2 more fixed

* made the package versions exact

* put `beartype` into requirements.txt and removed it from requirements_dev.txt because it is already included in requirements.txt

* updated coverage because a patch was available

* formatted with isort

* formatted with isort and removed unused imports

* fixed dict typing and added `process` that was missing before

* fixed dict typing for material.py

* telling mypy to ignore some types

* ignoring typing error for getters because within setters and constructor we require the correct value, however, in case it would be None, it would break everything. In the future we should try to figure out if we can fix this so the typings always work without us having to ignore them

* fixed api mypy typing errors

* formatted with trunk

* fixing imports with isort

* fix overshadow

* ignore this type

* fix ingredient keyword

* fix material compF and parent

* make collection pass

* fix condition

* fix material test

* fix property

* check for none

* fix project test

* fix more subobjects

* add half the UID deserialization support (random order is missing)

* make mypy trunk required

* reduce test number

* trunk merge q

* changing the package to exact version

---------

Co-authored-by: Ludwig Schneider <ludwigschneider@uchicago.edu>