mostly fixed mypy static type hinting errors for algorithm.py
properties that have `.copy()` at the end and they are optional are giving errors because we could be calling `None.copy()`

mypy gave an error of:
```
 error: Item "None" of "Optional[List[Any]]" has no attribute "copy"  [union-attr]
 ```